### PR TITLE
Modify PROTO files to be compatible with Webots R2018b

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Modify PROTO files to be compatible with Webots R2018b:

* invalid VRML comments (starting with '#') are no longer supported, Lua '--' prefix has to be used instead
* add 'static' tag needed to speed up the reset of the simulation needed in particular on the web interface
* remove lua code from Referee.proto that is no longer required: by the way the warnings about missing matching IS field can be suppressed using `unconnectedField` keyword instead of `field` in the declaration.

### CODE REVIEW

**Comment by chshong** [comment]
Shall I add static tag to SoccerField5v5.proto, Banners.proto, SoccerBallOrangeShape.proto, SoccerBallShape.proto, and color protos? Is there a particular reason that these protos need not (or must not) have the static tag?

**Comment by chshong** [comment]
Is it okay to add static tag to Placement.proto? It uses math.random to randomly add spectator models to the stadium.

**Comment by stefaniapedrazzi** [comment]
With the static flag, the spectators are still added randomly in the stadium when the simulation is open or when the world is completely reloaded (desktop version only), i.e. when pressing this button

but the stadium is not regenerated when the simulation is reset from the web interface using this button:


So it is strongly suggested to use this flag also for `Placement.proto` because recreating the whole stadium could take long.

**Comment by chshong** [comment]
Ah, got it. Thank you.

Shall I put the static flag also to Banners.proto then? It includes some procedural parts.

**Comment by stefaniapedrazzi** [comment]
Yes, it would be good to add the static tag to all the procedural PROTO files.

**Comment by chshong** [comment]
Would it also be meaningful for adding the tag to the soccerrobot protos too? Would it not be meaningful since the same proto is used ten times with different field values to place ten robots?

**Comment by stefaniapedrazzi** [comment]
Yes these are the other PROTO files to which it would be good to add the static flag as well:
* SoccerRobot.proto
* SoccerRobotNumberPatch.proto
* SoccerRobotIDPatch.proto

The static tag is not a problem for PROTO models used many times as soon as they doesn't contain any random functionality.
This tag tells Webots that the PROTO model can be read and evaluated only once for all the instances.
But it has not to be used if you want that all the instances use a different random functionality.

**Pull request merged**
