### PR TITLE
Signed world and proto files for use with free version of Webots

### PR DESCRIPTION
**Pull request by omichel**
As discussed before, here is the PR signing the world file and the various proto files.

Each time a proto or world file is modified, the corresponding signature files need to be re-generated, so that the world file can be opened in the free version of Webots.

👍

### CODE REVIEW

**Comment by chshong** [comment]
Given that the supervisor does not have a signature, is it possible for me to modify and recompile the supervisor without asking you to sign the system again?

**Comment by omichel** [comment]
No, the supervisor should be signed as well. I didn't signed on this branch because it needs to be recompiled with Webots R2018a revision 1 before being signed. I will sign it when we release Webots R2018a revision 1.

**Comment by chshong** [comment]
Ok. Will it be available before April as I would like to test the signed version before opening the competition?

**Comment by omichel** [comment]
Yes, we will release a beta version for you next week or so.

**Pull request merged**
