### PR TITLE
Simplify cross-platform compatibility

### PR DESCRIPTION
**Pull request by omichel**
Replaces #18, taking into account Python controllers and targeting the develop branch of `aiwc/test_world`.

👍

### CODE REVIEW

**Comment by chshong** [comment]
Thinking about using config.json to provide the executable path, it can be possible that adding ".exe" automatically may confuse the windows users now. So I am thinking of dropping that part and inform the users how to use the configuration file instead.

**Comment by omichel** [comment]
Alternatively, we could support both cases on Windows:

- if the config.json contains a reference to an executable with the ".exe" extension, use it as is (e.g., don't add an extra ".exe").
- if the config.json contains a reference to an executable without the ".exe" extension, append ".exe" to it before using it.

That would be more robust and allows (in the second case) to have a config.json file that is cross-platform while the first case is easier to understand for users.

But if you prefer to totally drop the second case, this is also fine. It should not raise any particular problem.

**Comment by chshong** [comment]
While I was testing the system in Windows, I found that our AI world cup simulation is capable of running an Windows executable program even if the program lacks ".exe" extension or having any other extensions such as ".rar" (It seems boost::process used for running the user program as a child process is allowing it).

Now my concern is that a user may try to make a participant executable program that does not have ".exe" extension (which will actually work in our simulation) and our supervisor would automatically attach ".exe" to the program path and output "no such file or directory".

**Comment by omichel** [comment]
In that case, I believe we should remove the automatic adding of the ".exe" extension from the supervisor and it will work in both cases (when the user specifies a "controller.exe" or a "controller" file).

**Comment by chshong** [comment]
I see. Then, current develop branch will be good to proceed signing the world file.

**Comment by omichel** [comment]
Yes, I will do it today.

**Pull request merged**
